/**
 * Fixture de QA manual — schema real (ACADY / plano de aula TBL) fornecido pra
 * validar o renderer. Usado SOMENTE quando `localStorage['wif-mock'] === '1'`
 * e o agente ativo não tiver `input_form`. Não afeta produção.
 *
 * TODO(temporário): remover quando o waves-core passar a entregar `input_form`
 * no payload de login dos agentes.
 */
export const SAMPLE_INPUT_FORM: unknown[] = [
  { type: "header", subtype: "h4", label: "Informações básicas", column: "12" },
  {
    type: "text",
    required: true,
    label: "Título da aula",
    className: "form-control",
    name: "titulo-aula",
    subtype: "text",
    column: "4",
  },
  {
    type: "date",
    required: true,
    label: "Data&nbsp;",
    className: "form-control",
    name: "data",
    column: "4",
  },
  {
    type: "select",
    required: true,
    label: "Modalidade",
    className: "form-control",
    name: "modalidade",
    multiple: false,
    column: "4",
    values: [
      { label: "Presencial", value: "presencial", selected: true },
      { label: "Remota", value: "remota", selected: false },
      { label: "Híbrida", value: "hibrida", selected: false },
      { label: "EAD", value: "EAD", selected: false },
      { label: "Semi-presencial", value: "Semi-presencial", selected: false },
    ],
  },
  { type: "header", subtype: "h4", label: "Habilidade do aprendizado", column: "12" },
  {
    type: "paragraph",
    subtype: "p",
    label: "Códigos alfanuméricos criados para identificar tais aprendizagens na BNCC.",
    className: "small",
    column: "12",
  },
  {
    type: "select",
    required: false,
    label: "Componente Curricular",
    className: "form-control",
    name: "componente-curricular",
    multiple: false,
    column: "12",
    values: [
      { label: "Option 1", value: "option-1", selected: true },
      { label: "Option 2", value: "option-2", selected: false },
      { label: "Option 3", value: "option-3", selected: false },
    ],
  },
  {
    type: "select",
    required: false,
    label: "Ano",
    className: "form-control",
    name: "ano-faixa",
    multiple: false,
    column: "12",
    values: [
      { label: "Option 1", value: "option-1", selected: true },
      { label: "Option 2", value: "option-2", selected: false },
      { label: "Option 3", value: "option-3", selected: false },
    ],
  },
  {
    type: "select",
    required: false,
    label: "Habilidade",
    className: "form-control",
    name: "habilidade",
    multiple: false,
    column: "12",
    values: [
      { label: "Option 1", value: "option-1", selected: true },
      { label: "Option 2", value: "option-2", selected: false },
      { label: "Option 3", value: "option-3", selected: false },
    ],
  },
  {
    type: "text",
    required: false,
    label: "Unidades Temáticas",
    className: "form-control",
    name: "unidades-tematicas",
    subtype: "text",
    column: "12",
    readonly: true,
  },
  {
    type: "text",
    required: false,
    label: "Objetos de Conhecimento",
    className: "form-control",
    name: "objetos-conhecimento",
    subtype: "text",
    column: "12",
    readonly: true,
  },
  {
    type: "text",
    required: false,
    label: "Práticas",
    className: "form-control",
    name: "praticas",
    subtype: "text",
    column: "12",
    readonly: true,
  },
  {
    type: "text",
    required: false,
    label: "Campos de Atuação",
    className: "form-control",
    name: "campos-atuacao",
    subtype: "text",
    column: "12",
    readonly: true,
  },
  {
    type: "text",
    required: false,
    label: "Objetivos",
    className: "form-control",
    name: "objetivos",
    subtype: "text",
    column: "12",
    readonly: true,
  },
  {
    type: "text",
    required: false,
    label: "Áreas de Conhecimento",
    className: "form-control",
    name: "areas-conhecimento",
    subtype: "text",
    column: "12",
    readonly: true,
  },
  {
    type: "text",
    required: false,
    label: "Competências Específicas",
    className: "form-control",
    name: "competencias-especificas",
    subtype: "text",
    column: "12",
    readonly: true,
  },
  {
    type: "textarea",
    required: true,
    label: "Descrição",
    className: "form-control",
    name: "descricao",
    subtype: "textarea",
    rows: 5,
    column: "12",
  },
  { type: "break", required: false, name: "break-1698348072537-0", column: "12" },
  { type: "header", subtype: "h4", label: "Aprendizagem Baseada em Equipes", column: "4" },
  {
    type: "button",
    label: "Gerador AI",
    subtype: "button",
    className: "btn-default btn ai-generator",
    name: "ai-generator",
    style: "default",
  },
  {
    type: "text",
    required: true,
    label: "Tema da Aula",
    className: "form-control ai-target",
    name: "tema-aula",
    subtype: "text",
    column: "12",
    prompt:
      "Com base em todas as informações pedagógicas previamente preenchidas na plataforma ACADY, elabore o Tema da Aula utilizando a metodologia de Aprendizagem Baseada em times (TBL).",
  },
  {
    type: "number",
    required: true,
    label: "Duração da Atividade",
    className: "form-control ai-target",
    name: "duracao-atividade",
    value: "4",
    min: 1,
    max: 16,
    step: 1,
    column: "4",
  },
  {
    type: "select",
    required: true,
    label: "Unidade de Tempo",
    className: "form-control ai-target",
    name: "unidade-tempo",
    multiple: false,
    column: "4",
    values: [
      { label: "Aula(s)", value: "aulas", selected: true },
      { label: "Semana(s)", value: "semanas", selected: false },
      { label: "Mes(es)", value: "meses", selected: false },
      { label: "Semestre(s)", value: "semestres", selected: false },
      { label: "Semi-presencial", value: "semi-presencial", selected: false },
    ],
  },
  {
    type: "textarea",
    required: false,
    label: "Objetivo de Aprendizagem",
    className: "form-control ai-target",
    name: "objetivo-aprendizagem",
    subtype: "textarea",
    rows: 4,
    column: "4",
    prompt:
      "Com base no tema da aula e nas competências e habilidades da BNCC, elabore de 1 a 3 Objetivos de Aprendizagem para uma aula TBL.",
  },
  {
    type: "select",
    required: true,
    label: "Atividade Prévia&nbsp;",
    className: "form-control ai-target",
    name: "atividade-previa",
    multiple: true,
    column: "4",
    values: [
      { label: "Não haverá", value: "nao-havera", selected: false },
      { label: "Assistir a um video", value: "assistir-video", selected: false },
      { label: "Mapa mental", value: "mapa mental", selected: false },
      { label: "Mapa conceitual", value: "Mapa conceitual", selected: false },
      { label: "Ler um artigo", value: "ler-artigo", selected: false },
      { label: "Fazer uma colagem", value: "fazer-colagem", selected: false },
      { label: "Analise de caso", value: "analise de caso", selected: false },
      { label: "Sintese conceitual", value: "sintese-conceitual", selected: false },
      { label: "Tirar fotos", value: "tirar-fotos", selected: true },
      { label: "Coleta de material", value: "coleta-material", selected: false },
    ],
  },
  {
    type: "select",
    required: true,
    label: "Haverá Entrega Prévia de Atividade?",
    className: "form-control ai-target",
    name: "havera-entrega-previa-atividade",
    multiple: false,
    column: "4",
    values: [
      { label: "Sim", value: "sim", selected: false },
      { label: "Não", value: "não", selected: false },
    ],
  },
  {
    type: "text",
    required: true,
    label: "Questões Trabalhadas",
    className: "form-control ai-target",
    name: "questes-trabalhadas",
    subtype: "text",
    column: "4",
    prompt:
      "Com base no tema da aula e nos objetivos de aprendizagem, gere 4 questões de múltipla escolha no formato TBL (iRAT/tRAT).",
  },
  {
    type: "autocomplete",
    required: true,
    label: "Avaliação",
    className: "avaliacao",
    name: "avaliacao",
    requireValidOption: true,
    column: "12",
    values: [
      { label: "Individual", value: "individual", selected: true },
      { label: "Em Grupo", value: "em-grupo", selected: false },
    ],
  },
];

/** Envelope com submit_button_text (formato que o waves-core deve entregar). */
export const SAMPLE_INPUT_FORM_ENVELOPE = {
  submit_button_text: "Gerar plano de aula",
  fields: SAMPLE_INPUT_FORM,
};
